import { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';
import { ListGroup } from 'react-bootstrap';
import './InfoModal.css';

function InfoModal() {
  const [show, setShow] = useState(true);
  const handleClose = () => setShow(false);

  return (
    <>
      <Modal
        show={show}
        onHide={handleClose}
        backdrop="static"
        keyboard={false}
        dialogClassName="info-modal-content"
      >
        {/* Removed redundant Bootstrap classes from Modal.Header */}
        <Modal.Header closeButton>
          <Modal.Title>Welcome to Galactic Fleet Battles!</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p className="text-center lead mb-4">Assemble a fleet of starships and play against different enemies</p>
          
          <h5 className="mb-3 text-center">How to play</h5>
          <ListGroup variant="flush">
            <ListGroup.Item className='text-center'>
              Build A Fleet: Choose starships from 3 different classes, with each having their own advantages
            </ListGroup.Item>
            <ListGroup.Item className='text-center'>
              Enter The Battle: Once you've clicked "Deploy", you cannot change your fleet. Choose wisely!
            </ListGroup.Item>
            <ListGroup.Item className='text-center'>
              Fight The Enemy: Attack an enemy class with one of your own, but be prepared for them to attack back
            </ListGroup.Item>
            <ListGroup.Item className='text-center'>
              Battle Analysis: After each skirmish, you'll receive a narrative battle report generated by Google Gemini
            </ListGroup.Item>
          </ListGroup>
        </Modal.Body>
        <Modal.Footer className='justify-content-center'>
          <Button variant="primary" onClick={handleClose}>Understood</Button>
        </Modal.Footer>
      </Modal>
    </>
  );
} 

export default InfoModal;