import { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';
import { ListGroup } from 'react-bootstrap';

function InfoModal() {
  const [show, setShow] = useState(true);
  const handleClose = () => setShow(false);

  return (
    <>
      <Modal
        show={show}
        onHide={handleClose}
        backdrop="static"
        keyboard={false}
      >
        <Modal.Header closeButton className="d-flex justify-content-center">
          <Modal.Title className='flex-grow-1 text-center'>Welcome to Galactic Fleet Battles!</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p className="text-center lead mb-4">Assemble a fleet of starships and test their might against different factions from Star Wars!</p>
          
          <h5 className="mb-3 text-center">Key Intel</h5>
          <ListGroup variant="flush">
            <ListGroup.Item className='text-center'>
              Build A Fleet: Choose your armada from 18 iconic Star Wars ships, balancing speed and power to win.
            </ListGroup.Item>
            <ListGroup.Item className='text-center'>
              Strategic Deployment: Once you've clicked "Battle!", your fleet is locked in! No reinforcements can be added until the current engagement is over. Choose wisely, Admiral!
            </ListGroup.Item>
            <ListGroup.Item className='text-center'>
              Create An Account: Test your skills against a small pirate fleet, then log in to unlock greater challenges and view fleet information on My Fleet page.
            </ListGroup.Item>
            <ListGroup.Item className='text-center'>
              Battle Analysis: After each skirmish, you'll receive a detailed battle report generated by Google Gemini, providing insights into your fleet's performance.
            </ListGroup.Item>
          </ListGroup>
        </Modal.Body>
        <Modal.Footer className='justify-content-center'>
          <Button variant="primary" onClick={handleClose}>Understood</Button>
        </Modal.Footer>
      </Modal>
    </>
  );
} 

export default InfoModal;